i care not for volta

diff --git a/.chezmoiscripts/run_after_31-install-volta-packages.sh.tmpl b/.chezmoiscripts/run_after_31-install-volta-packages.sh.tmpl
--- a/.chezmoiscripts/run_after_31-install-volta-packages.sh.tmpl
+++ b/.chezmoiscripts/run_after_31-install-volta-packages.sh.tmpl
@@ -7,23 +7,23 @@
 true || source ../.chezmoitemplates/scripts-library
 true || source ../.chezmoitemplates/volta-library
 
-readonly desired_packages=(
-  node
-  npm
-  yarn
-  @vscode/dev-container-cli
-)
+# readonly desired_packages=(
+#   node
+#   npm
+#   yarn
+#   @vscode/dev-container-cli
+# )
 
-missing_packages=()
+# missing_packages=()
 
-for package in "${desired_packages[@]}"; do
-  # shellcheck disable=SC2312
-  if ! volta list --current --quiet --format plain "${package}" | grep --quiet .; then
-    missing_packages+=("${package}")
-  fi
-done
+# for package in "${desired_packages[@]}"; do
+#   # shellcheck disable=SC2312
+#   if ! volta list --current --quiet --format plain "${package}" | grep --quiet .; then
+#     missing_packages+=("${package}")
+#   fi
+# done
 
-if [[ ${#missing_packages[@]} -gt 0 ]]; then
-  log_task "Installing missing packages with Volta: ${missing_packages[*]}"
-  volta install "${missing_packages[@]}"
-fi
+# if [[ ${#missing_packages[@]} -gt 0 ]]; then
+#   log_task "Installing missing packages with Volta: ${missing_packages[*]}"
+#   volta install "${missing_packages[@]}"
+# fi
